using System.Collections.ObjectModel;
using System.IO;
using System.Text;
using System.Text.Json;
using Microsoft.Win32;
using Spexts.Models;

namespace Spexts.Helpers;

public static class ExportHelper
{
    public static void Export(string format,
        params (string PanelName, ObservableCollection<InfoRow> Rows)[] panels)
    {
        var dialog = new SaveFileDialog();

        if (format == "JSON")
        {
            dialog.Filter = "JSON Files (*.json)|*.json|All Files (*.*)|*.*";
            dialog.DefaultExt = ".json";
        }
        else
        {
            dialog.Filter = "Text Files (*.txt)|*.txt|All Files (*.*)|*.*";
            dialog.DefaultExt = ".txt";
        }

        dialog.FileName = $"Spexts_Report_{DateTime.Now:yyyyMMdd_HHmmss}";

        if (dialog.ShowDialog() == true)
        {
            try
            {
                if (format == "JSON")
                    ExportJson(dialog.FileName, panels);
                else
                    ExportTxt(dialog.FileName, panels);

                System.Windows.MessageBox.Show(
                    $"Report exported successfully to:\n{dialog.FileName}",
                    "Spexts — Export Complete",
                    System.Windows.MessageBoxButton.OK,
                    System.Windows.MessageBoxImage.Information);
            }
            catch (Exception ex)
            {
                System.Windows.MessageBox.Show(
                    $"Export failed: {ex.Message}", "Spexts",
                    System.Windows.MessageBoxButton.OK,
                    System.Windows.MessageBoxImage.Error);
            }
        }
    }

    private static void ExportTxt(string path,
        (string PanelName, ObservableCollection<InfoRow> Rows)[] panels)
    {
        var sb = new StringBuilder();
        sb.AppendLine("╔══════════════════════════════════════════════════════════════╗");
        sb.AppendLine("║                    SPEXTS DIAGNOSTICS REPORT                ║");
        sb.AppendLine("╚══════════════════════════════════════════════════════════════╝");
        sb.AppendLine();
        sb.AppendLine($"  Generated : {DateTime.Now:yyyy-MM-dd HH:mm:ss}");
        sb.AppendLine($"  Machine   : {Environment.MachineName}");
        sb.AppendLine($"  User      : {Environment.UserName}");
        sb.AppendLine();

        foreach (var (panelName, rows) in panels)
        {
            sb.AppendLine($"┌─ {panelName} {"".PadRight(55 - panelName.Length, '─')}");
            sb.AppendLine("│");
            foreach (var row in rows)
            {
                sb.AppendLine($"│  {row.Label,-28} {row.Value}");
            }
            sb.AppendLine("│");
            sb.AppendLine("└──────────────────────────────────────────────────────────────");
            sb.AppendLine();
        }

        sb.AppendLine("  End of Report — Generated by Spexts");
        File.WriteAllText(path, sb.ToString(), Encoding.UTF8);
    }

    private static void ExportJson(string path,
        (string PanelName, ObservableCollection<InfoRow> Rows)[] panels)
    {
        var report = new Dictionary<string, object>
        {
            ["report"] = "Spexts Diagnostics Report",
            ["generated"] = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss"),
            ["machine"] = Environment.MachineName,
            ["user"] = Environment.UserName
        };

        foreach (var (panelName, rows) in panels)
        {
            var section = new Dictionary<string, string>();
            foreach (var row in rows)
            {
                section[row.Label] = row.Value;
            }
            report[panelName] = section;
        }

        var options = new JsonSerializerOptions { WriteIndented = true };
        var json = JsonSerializer.Serialize(report, options);
        File.WriteAllText(path, json, Encoding.UTF8);
    }
}
